# Generated by Django 3.2.17 on 2023-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(verbose_name=12)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('looking_for', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
