# Generated by Django 4.1.7 on 2023-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0002_auto_20230228_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('proof_of_id', models.CharField(max_length=200)),
                ('proof_of_address', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=100)),
                ('religion_category', models.CharField(max_length=100)),
                ('cast_category', models.CharField(max_length=100)),
                ('income', models.IntegerField(verbose_name=10)),
                ('height', models.IntegerField(verbose_name=10)),
                ('weight', models.IntegerField(verbose_name=10)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
