# Generated by Django 3.2.25 on 2024-05-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0005_users11_confirm_password_users11_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users11',
            new_name='User',
        ),
    ]
