# Generated by Django 3.2.25 on 2024-05-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0006_rename_users11_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
