# Generated by Django 3.2.25 on 2024-05-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0007_remove_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='proof_of_address',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='proof_of_id',
        ),
    ]
