# Generated by Django 3.2.25 on 2024-05-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0010_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic1', models.CharField(max_length=100)),
                ('profilepic2', models.CharField(max_length=100)),
                ('profilepic3', models.CharField(max_length=100)),
                ('profilepic4', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shadiusers.user')),
            ],
        ),
    ]
