# Generated by Django 3.2.25 on 2024-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0011_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profilepic1',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilepic2',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilepic3',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='profilepic4',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
