# Generated by Django 3.2.25 on 2024-05-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0012_auto_20240516_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(unique=True, verbose_name=12),
        ),
    ]
