# Generated by Django 3.2.25 on 2024-05-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0013_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('duration', models.IntegerField(verbose_name=10)),
                ('users', models.IntegerField(verbose_name=10)),
                ('price', models.IntegerField(verbose_name=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shadiusers.user')),
            ],
        ),
    ]
