# Generated by Django 3.2.25 on 2024-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0014_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='plan',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
