# Generated by Django 3.2.25 on 2024-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiusers', '0015_alter_subscribe_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-01 12:30:00'),
            preserve_default=False,
        ),
    ]
