# Generated by Django 4.1 on 2023-02-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadiadmin", "0002_education_mothertongue_occupation_religion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
