# Generated by Django 4.1 on 2023-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadiadmin", "0003_alter_users_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="mobile",
            field=models.BigIntegerField(verbose_name=12),
        ),
    ]
