# Generated by Django 4.1 on 2023-02-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shadiadmin", "0004_alter_users_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="users",
            name="updated_date",
        ),
    ]
