# Generated by Django 4.1 on 2023-02-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadiadmin", "0005_remove_users_created_date_remove_users_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="religion",
            name="sub_category",
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
