# Generated by Django 4.1 on 2023-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadiadmin", "0006_religion_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="dob",
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
