# Generated by Django 4.1 on 2023-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadiadmin", "0007_users_address_users_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="dob",
            field=models.DateField(),
        ),
    ]
