# Generated by Django 3.2.17 on 2023-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadiadmin', '0008_alter_users_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='name',
            new_name='occupation_name',
        ),
        migrations.RenameField(
            model_name='religion_category',
            old_name='cast_name',
            new_name='religion_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='religion_category',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='religion_category',
            name='subid',
        ),
        migrations.AddField(
            model_name='religion_category',
            name='sub_category',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
