# Generated by Django 3.2.17 on 2023-02-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadiadmin', '0009_auto_20230223_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='sub_id',
            new_name='sub_category',
        ),
    ]
